root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./main.go"
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "docs", ".git"]
delay = 500
stop_on_error = true

[log]
time = true
